/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContestCreation.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ContestCreation::ContestCreation() {
  m_File_input = "";
  m_File_output = "";
  m_Description = "";
  m_DescriptionIsSet = false;
}

ContestCreation::~ContestCreation() {}

void ContestCreation::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ContestCreation& o) {
  j = nlohmann::json();
  j["file_input"] = o.m_File_input;
  j["file_output"] = o.m_File_output;
  if (o.descriptionIsSet()) j["description"] = o.m_Description;
}

void from_json(const nlohmann::json& j, ContestCreation& o) {
  j.at("file_input").get_to(o.m_File_input);
  j.at("file_output").get_to(o.m_File_output);
  if (j.contains("description")) {
    j.at("description").get_to(o.m_Description);
    o.m_DescriptionIsSet = true;
  }
}

std::string ContestCreation::getFileInput() const { return m_File_input; }
void ContestCreation::setFileInput(std::string const& value) {
  m_File_input = value;
}
std::string ContestCreation::getFileOutput() const { return m_File_output; }
void ContestCreation::setFileOutput(std::string const& value) {
  m_File_output = value;
}
std::string ContestCreation::getDescription() const { return m_Description; }
void ContestCreation::setDescription(std::string const& value) {
  m_Description = value;
  m_DescriptionIsSet = true;
}
bool ContestCreation::descriptionIsSet() const { return m_DescriptionIsSet; }
void ContestCreation::unsetDescription() { m_DescriptionIsSet = false; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
