/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContestIdObject.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ContestIdObject::ContestIdObject() { m_ContestId = 0; }

ContestIdObject::~ContestIdObject() {}

void ContestIdObject::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const ContestIdObject& o) {
  j = nlohmann::json();
  j["ContestId"] = o.m_ContestId;
}

void from_json(const nlohmann::json& j, ContestIdObject& o) {
  j.at("ContestId").get_to(o.m_ContestId);
}

int32_t ContestIdObject::getContestId() const { return m_ContestId; }
void ContestIdObject::setContestId(int32_t const value) { m_ContestId = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
