/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ContestCreation.h
 *
 *
 */

#ifndef ContestCreation_H_
#define ContestCreation_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ContestCreation {
 public:
  ContestCreation();
  virtual ~ContestCreation();

  void validate();

  /////////////////////////////////////////////
  /// ContestCreation members

  /// <summary>
  ///
  /// </summary>
  std::string getFileInput() const;
  void setFileInput(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getFileOutput() const;
  void setFileOutput(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getDescription() const;
  void setDescription(std::string const& value);
  bool descriptionIsSet() const;
  void unsetDescription();

  friend void to_json(nlohmann::json& j, const ContestCreation& o);
  friend void from_json(const nlohmann::json& j, ContestCreation& o);

 protected:
  std::string m_File_input;

  std::string m_File_output;

  std::string m_Description;
  bool m_DescriptionIsSet;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* ContestCreation_H_ */
