/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PackageId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PackageId::PackageId() { m_PackageId = 0; }

PackageId::~PackageId() {}

void PackageId::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const PackageId& o) {
  j = nlohmann::json();
  j["PackageId"] = o.m_PackageId;
}

void from_json(const nlohmann::json& j, PackageId& o) {
  j.at("PackageId").get_to(o.m_PackageId);
}

int32_t PackageId::getPackageId() const { return m_PackageId; }
void PackageId::setPackageId(int32_t const value) { m_PackageId = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
