/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PackageCreation.h
 *
 *
 */

#ifndef PackageCreation_H_
#define PackageCreation_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class PackageCreation {
 public:
  PackageCreation();
  virtual ~PackageCreation();

  void validate();

  /////////////////////////////////////////////
  /// PackageCreation members

  /// <summary>
  ///
  /// </summary>
  std::string getFile() const;
  void setFile(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getContestId() const;
  void setContestId(int32_t const value);

  friend void to_json(nlohmann::json& j, const PackageCreation& o);
  friend void from_json(const nlohmann::json& j, PackageCreation& o);

 protected:
  std::string m_file;

  int32_t m_Contest_id;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* PackageCreation_H_ */
