/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PackageCreation.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PackageCreation::PackageCreation() {
  m_file = "";
  m_Contest_id = 0;
}

PackageCreation::~PackageCreation() {}

void PackageCreation::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const PackageCreation& o) {
  j = nlohmann::json();
  j["file"] = o.m_file;
  j["contest_id"] = o.m_Contest_id;
}

void from_json(const nlohmann::json& j, PackageCreation& o) {
  j.at("file").get_to(o.m_file);
  j.at("contest_id").get_to(o.m_Contest_id);
}

std::string PackageCreation::getFile() const { return m_file; }
void PackageCreation::setFile(std::string const& value) { m_file = value; }
int32_t PackageCreation::getContestId() const { return m_Contest_id; }
void PackageCreation::setContestId(int32_t const value) {
  m_Contest_id = value;
}

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
