/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PackageId.h
 *
 *
 */

#ifndef PackageId_H_
#define PackageId_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class PackageId {
 public:
  PackageId();
  virtual ~PackageId();

  void validate();

  /////////////////////////////////////////////
  /// PackageId members

  /// <summary>
  ///
  /// </summary>
  int32_t getPackageId() const;
  void setPackageId(int32_t const value);

  friend void to_json(nlohmann::json& j, const PackageId& o);
  friend void from_json(const nlohmann::json& j, PackageId& o);

 protected:
  int32_t m_PackageId;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* PackageId_H_ */
