/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SessionIdObject.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SessionIdObject::SessionIdObject() { m_SessionId = 0; }

SessionIdObject::~SessionIdObject() {}

void SessionIdObject::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const SessionIdObject& o) {
  j = nlohmann::json();
  j["SessionId"] = o.m_SessionId;
}

void from_json(const nlohmann::json& j, SessionIdObject& o) {
  j.at("SessionId").get_to(o.m_SessionId);
}

int32_t SessionIdObject::getSessionId() const { return m_SessionId; }
void SessionIdObject::setSessionId(int32_t const value) { m_SessionId = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
