/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SessionIdObject.h
 *
 *
 */

#ifndef SessionIdObject_H_
#define SessionIdObject_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class SessionIdObject {
 public:
  SessionIdObject();
  virtual ~SessionIdObject();

  void validate();

  /////////////////////////////////////////////
  /// SessionIdObject members

  /// <summary>
  ///
  /// </summary>
  int32_t getSessionId() const;
  void setSessionId(int32_t const value);

  friend void to_json(nlohmann::json& j, const SessionIdObject& o);
  friend void from_json(const nlohmann::json& j, SessionIdObject& o);

 protected:
  int32_t m_SessionId;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* SessionIdObject_H_ */
