/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Solution.h
 *
 *
 */

#ifndef Solution_H_
#define Solution_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Solution {
 public:
  Solution();
  virtual ~Solution();

  void validate();

  /////////////////////////////////////////////
  /// Solution members

  /// <summary>
  ///
  /// </summary>
  std::string getLog() const;
  void setLog(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getResult() const;
  void setResult(std::string const& value);

  friend void to_json(nlohmann::json& j, const Solution& o);
  friend void from_json(const nlohmann::json& j, Solution& o);

 protected:
  std::string m_Log;

  std::string m_Result;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* Solution_H_ */
