/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Solution.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Solution::Solution() {
  m_Log = "";
  m_Result = "";
}

Solution::~Solution() {}

void Solution::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const Solution& o) {
  j = nlohmann::json();
  j["log"] = o.m_Log;
  j["result"] = o.m_Result;
}

void from_json(const nlohmann::json& j, Solution& o) {
  j.at("log").get_to(o.m_Log);
  j.at("result").get_to(o.m_Result);
}

std::string Solution::getLog() const { return m_Log; }
void Solution::setLog(std::string const& value) { m_Log = value; }
std::string Solution::getResult() const { return m_Result; }
void Solution::setResult(std::string const& value) { m_Result = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
