/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UserData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UserData::UserData() {
  m_Name = "";
  m_Password = "";
}

UserData::~UserData() {}

void UserData::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const UserData& o) {
  j = nlohmann::json();
  j["name"] = o.m_Name;
  j["password"] = o.m_Password;
}

void from_json(const nlohmann::json& j, UserData& o) {
  j.at("name").get_to(o.m_Name);
  j.at("password").get_to(o.m_Password);
}

std::string UserData::getName() const { return m_Name; }
void UserData::setName(std::string const& value) { m_Name = value; }
std::string UserData::getPassword() const { return m_Password; }
void UserData::setPassword(std::string const& value) { m_Password = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
