/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * HumanApi.h
 *
 *
 */

#ifndef HumanApi_H_
#define HumanApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>
#include <pistache/router.h>

#include "SessionIdObject.h"
#include "UserData.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class HumanApi {
 public:
  HumanApi(std::shared_ptr<Pistache::Rest::Router>);
  virtual ~HumanApi() {}
  void init();

  const std::string base = "/tp-contest/NewTP-COntestAPI/1.0.0";

 private:
  void setupRoutes();

  void human_create_handler(const Pistache::Rest::Request &request,
                            Pistache::Http::ResponseWriter response);
  void human_api_default_handler(const Pistache::Rest::Request &request,
                                 Pistache::Http::ResponseWriter response);

  std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Lets register user
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="userData"></param>
  virtual void human_create(const UserData &userData,
                            Pistache::Http::ResponseWriter &response) = 0;
};

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* HumanApi_H_ */
