/**
 * TP-Contest Backend
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ContestApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ContestApiImpl::ContestApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : ContestApi(rtr) {}

void ContestApiImpl::create_contest(const Pistache::Rest::Request &request,
                                    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void ContestApiImpl::get_solution(const Pistache::Optional<int32_t> &sessionId,
                                  const Pistache::Optional<int32_t> &contestId,
                                  Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void ContestApiImpl::send_task(const Pistache::Rest::Request &request,
                               Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org
