/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "WorkerApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace worker_server::helper;
using namespace org::openapitools::server::model;

WorkerApi::WorkerApi(std::shared_ptr<Pistache::Rest::Router> rtr) {
  router = rtr;
};

void WorkerApi::init() { setupRoutes(); }

void WorkerApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(*router, base + "/freeSlots",
              Routes::bind(&WorkerApi::free_slots_handler, this));
  Routes::Post(*router, base + "/sendTask",
               Routes::bind(&WorkerApi::send_task_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(
      Routes::bind(&WorkerApi::worker_api_default_handler, this));
}

void WorkerApi::free_slots_handler(const Pistache::Rest::Request &request,
                                   Pistache::Http::ResponseWriter response) {
  try {
    this->free_slots(response);
  } catch (std::runtime_error &e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  }
}
void WorkerApi::send_task_handler(const Pistache::Rest::Request &request,
                                  Pistache::Http::ResponseWriter response) {
  // Getting the body param
  std::vector<Task> task;

  try {
    nlohmann::json::parse(request.body()).get_to(task);
    this->send_task(task, response);
  } catch (std::runtime_error &e) {
    // send a 400 error
    response.send(Pistache::Http::Code::Bad_Request, e.what());
    return;
  }
}

void WorkerApi::worker_api_default_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org
