/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SchedulerApi.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_SchedulerApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_SchedulerApi_H_

#include "../ApiClient.h"

#include "Task.h"

#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;

class SchedulerApi {
 public:
  explicit SchedulerApi(std::shared_ptr<ApiClient> apiClient);

  virtual ~SchedulerApi();

  /// <summary>
  ///
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="task"> (optional)</param>
  pplx::task<void> sendTask(boost::optional<std::shared_ptr<Task>> task);

 protected:
  std::shared_ptr<ApiClient> m_ApiClient;
};

}  // namespace api
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_API_SchedulerApi_H_ */
