/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Slot.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Slot::Slot() {
  m_Name = "";
  m_Count = 0;
}

Slot::~Slot() {}

void Slot::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json& j, const Slot& o) {
  j = nlohmann::json();
  j["name"] = o.m_Name;
  j["count"] = o.m_Count;
}

void from_json(const nlohmann::json& j, Slot& o) {
  j.at("name").get_to(o.m_Name);
  j.at("count").get_to(o.m_Count);
}

std::string Slot::getName() const { return m_Name; }
void Slot::setName(std::string const& value) { m_Name = value; }
int32_t Slot::getCount() const { return m_Count; }
void Slot::setCount(int32_t const value) { m_Count = value; }

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org
