/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Slot.h
 *
 *
 */

#ifndef Slot_H_
#define Slot_H_

#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Slot {
 public:
  Slot();
  virtual ~Slot();

  void validate();

  /////////////////////////////////////////////
  /// Slot members

  /// <summary>
  ///
  /// </summary>
  std::string getName() const;
  void setName(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getCount() const;
  void setCount(int32_t const value);

  friend void to_json(nlohmann::json& j, const Slot& o);
  friend void from_json(const nlohmann::json& j, Slot& o);

 protected:
  std::string m_Name;

  int32_t m_Count;
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* Slot_H_ */
