/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Slots.h
 *
 *
 */

#ifndef Slots_H_
#define Slots_H_

#include <nlohmann/json.hpp>
#include <vector>
#include "Slot.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class Slots {
 public:
  Slots();
  virtual ~Slots();

  void validate();

  /////////////////////////////////////////////
  /// Slots members

  friend void to_json(nlohmann::json& j, const Slots& o);
  friend void from_json(const nlohmann::json& j, Slots& o);

 protected:
};

}  // namespace model
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif /* Slots_H_ */
