/**
 * TP-Contest Worker
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * WorkerApiImpl.h
 *
 *
 */

#ifndef WORKER_API_IMPL_H_
#define WORKER_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <WorkerApi.h>

#include <pistache/optional.h>

#include <vector>
#include "Slots.h"
#include "Task.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class WorkerApiImpl : public org::openapitools::server::api::WorkerApi {
 public:
  WorkerApiImpl(std::shared_ptr<Pistache::Rest::Router>);
  ~WorkerApiImpl() {}

  void free_slots(Pistache::Http::ResponseWriter &response);
  void send_task(const std::vector<Task> &task,
                 Pistache::Http::ResponseWriter &response);
};

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org

#endif