/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SolutionId.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionId_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionId_H_

#include "../ModelBase.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class SolutionId : public ModelBase {
 public:
  SolutionId();
  virtual ~SolutionId();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t& namePrefix) const override;
  void fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// SolutionId members

  /// <summary>
  ///
  /// </summary>
  int32_t getSolutionId() const;

  void setSolutionId(int32_t value);

 protected:
  int32_t m_Solution_id;
};

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionId_H_ */
