/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SolutionFiles.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionFiles_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionFiles_H_

#include "../ModelBase.h"

#include "HttpContent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class SolutionFiles : public ModelBase {
 public:
  SolutionFiles();
  virtual ~SolutionFiles();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t& namePrefix) const override;
  void fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// SolutionFiles members

  /// <summary>
  ///
  /// </summary>
  HttpContent getLogFile() const;

  void setLogFile(const HttpContent& value);

  /// <summary>
  ///
  /// </summary>
  HttpContent getResultFile() const;

  void setResultFile(const HttpContent& value);

 protected:
  HttpContent m_Log_file;
  HttpContent m_Result_file;
};

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SolutionFiles_H_ */
