/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_

#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "UserData.h"
#include "UserId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class User : public ModelBase {
 public:
  User();
  virtual ~User();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  void fromJson(const web::json::value& json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t& namePrefix) const override;
  void fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t& namePrefix) override;

  /////////////////////////////////////////////
  /// User members

  /// <summary>
  ///
  /// </summary>
  int32_t getUserId() const;

  void setUserId(int32_t value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getUserPassword() const;

  void setUserPassword(const utility::string_t& value);

  /// <summary>
  ///
  /// </summary>
  utility::string_t getUserName() const;

  void setUserName(const utility::string_t& value);

 protected:
  int32_t m_User_id;
  utility::string_t m_User_password;
  utility::string_t m_User_name;
};

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_ */
