/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "SessionId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SessionId::SessionId() { m_Session_id = 0; }

SessionId::~SessionId() {}

void SessionId::validate() {
  // TODO: implement validation
}

web::json::value SessionId::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("session_id")] =
      ModelBase::toJson(m_Session_id);

  return val;
}

void SessionId::fromJson(const web::json::value& val) {
  setSessionId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("session_id"))));
}

void SessionId::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                            const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("session_id"),
      m_Session_id));
}

void SessionId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                              const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setSessionId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("session_id"))));
}

int32_t SessionId::getSessionId() const { return m_Session_id; }

void SessionId::setSessionId(int32_t value) { m_Session_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
