/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "SolutionData.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SolutionData::SolutionData() {
  m_Task_id = 0;
  m_Log_file_id = 0;
  m_Result_file_id = 0;
}

SolutionData::~SolutionData() {}

void SolutionData::validate() {
  // TODO: implement validation
}

web::json::value SolutionData::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("task_id")] =
      ModelBase::toJson(m_Task_id);
  val[utility::conversions::to_string_t("log_file_id")] =
      ModelBase::toJson(m_Log_file_id);
  val[utility::conversions::to_string_t("result_file_id")] =
      ModelBase::toJson(m_Result_file_id);

  return val;
}

void SolutionData::fromJson(const web::json::value& val) {
  setTaskId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("task_id"))));
  setLogFileId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("log_file_id"))));
  setResultFileId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("result_file_id"))));
}

void SolutionData::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("task_id"), m_Task_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("log_file_id"),
      m_Log_file_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("result_file_id"),
      m_Result_file_id));
}

void SolutionData::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                                 const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setTaskId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("task_id"))));
  setLogFileId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("log_file_id"))));
  setResultFileId(ModelBase::int32_tFromHttpContent(multipart->getContent(
      utility::conversions::to_string_t("result_file_id"))));
}

int32_t SolutionData::getTaskId() const { return m_Task_id; }

void SolutionData::setTaskId(int32_t value) { m_Task_id = value; }

int32_t SolutionData::getLogFileId() const { return m_Log_file_id; }

void SolutionData::setLogFileId(int32_t value) { m_Log_file_id = value; }

int32_t SolutionData::getResultFileId() const { return m_Result_file_id; }

void SolutionData::setResultFileId(int32_t value) { m_Result_file_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
