/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "TaskData.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TaskData::TaskData() {
  m_User_id = 0;
  m_Contest_id = 0;
  m_Task_file_id = 0;
}

TaskData::~TaskData() {}

void TaskData::validate() {
  // TODO: implement validation
}

web::json::value TaskData::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("user_id")] =
      ModelBase::toJson(m_User_id);
  val[utility::conversions::to_string_t("contest_id")] =
      ModelBase::toJson(m_Contest_id);
  val[utility::conversions::to_string_t("task_file_id")] =
      ModelBase::toJson(m_Task_file_id);

  return val;
}

void TaskData::fromJson(const web::json::value& val) {
  setUserId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("user_id"))));
  setContestId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("contest_id"))));
  setTaskFileId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("task_file_id"))));
}

void TaskData::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                           const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_id"), m_User_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("contest_id"),
      m_Contest_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("task_file_id"),
      m_Task_file_id));
}

void TaskData::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setUserId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("user_id"))));
  setContestId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("contest_id"))));
  setTaskFileId(ModelBase::int32_tFromHttpContent(multipart->getContent(
      utility::conversions::to_string_t("task_file_id"))));
}

int32_t TaskData::getUserId() const { return m_User_id; }

void TaskData::setUserId(int32_t value) { m_User_id = value; }

int32_t TaskData::getContestId() const { return m_Contest_id; }

void TaskData::setContestId(int32_t value) { m_Contest_id = value; }

int32_t TaskData::getTaskFileId() const { return m_Task_file_id; }

void TaskData::setTaskFileId(int32_t value) { m_Task_file_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
