/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "TaskId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

TaskId::TaskId() { m_Task_id = 0; }

TaskId::~TaskId() {}

void TaskId::validate() {
  // TODO: implement validation
}

web::json::value TaskId::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("task_id")] =
      ModelBase::toJson(m_Task_id);

  return val;
}

void TaskId::fromJson(const web::json::value& val) {
  setTaskId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("task_id"))));
}

void TaskId::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                         const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("task_id"), m_Task_id));
}

void TaskId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                           const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setTaskId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("task_id"))));
}

int32_t TaskId::getTaskId() const { return m_Task_id; }

void TaskId::setTaskId(int32_t value) { m_Task_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
