/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "User.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

User::User() {
  m_User_id = 0;
  m_User_password = utility::conversions::to_string_t("");
  m_User_name = utility::conversions::to_string_t("");
}

User::~User() {}

void User::validate() {
  // TODO: implement validation
}

web::json::value User::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("user_id")] =
      ModelBase::toJson(m_User_id);
  val[utility::conversions::to_string_t("user_password")] =
      ModelBase::toJson(m_User_password);
  val[utility::conversions::to_string_t("user_name")] =
      ModelBase::toJson(m_User_name);

  return val;
}

void User::fromJson(const web::json::value& val) {
  setUserId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("user_id"))));
  setUserPassword(ModelBase::stringFromJson(
      val.at(utility::conversions::to_string_t("user_password"))));
  setUserName(ModelBase::stringFromJson(
      val.at(utility::conversions::to_string_t("user_name"))));
}

void User::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                       const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_id"), m_User_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_password"),
      m_User_password));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_name"),
      m_User_name));
}

void User::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                         const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setUserId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("user_id"))));
  setUserPassword(ModelBase::stringFromHttpContent(multipart->getContent(
      utility::conversions::to_string_t("user_password"))));
  setUserName(ModelBase::stringFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("user_name"))));
}

int32_t User::getUserId() const { return m_User_id; }

void User::setUserId(int32_t value) { m_User_id = value; }

utility::string_t User::getUserPassword() const { return m_User_password; }

void User::setUserPassword(const utility::string_t& value) {
  m_User_password = value;
}

utility::string_t User::getUserName() const { return m_User_name; }

void User::setUserName(const utility::string_t& value) { m_User_name = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
