/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "UserId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UserId::UserId() { m_User_id = 0; }

UserId::~UserId() {}

void UserId::validate() {
  // TODO: implement validation
}

web::json::value UserId::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("user_id")] =
      ModelBase::toJson(m_User_id);

  return val;
}

void UserId::fromJson(const web::json::value& val) {
  setUserId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("user_id"))));
}

void UserId::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                         const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_id"), m_User_id));
}

void UserId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                           const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setUserId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("user_id"))));
}

int32_t UserId::getUserId() const { return m_User_id; }

void UserId::setUserId(int32_t value) { m_User_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
