/**
 * Pickle Rick API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "UserSessionId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UserSessionId::UserSessionId() {
  m_User_id = 0;
  m_Session_id = 0;
}

UserSessionId::~UserSessionId() {}

void UserSessionId::validate() {
  // TODO: implement validation
}

web::json::value UserSessionId::toJson() const {
  web::json::value val = web::json::value::object();

  val[utility::conversions::to_string_t("user_id")] =
      ModelBase::toJson(m_User_id);
  val[utility::conversions::to_string_t("session_id")] =
      ModelBase::toJson(m_Session_id);

  return val;
}

void UserSessionId::fromJson(const web::json::value& val) {
  setUserId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("user_id"))));
  setSessionId(ModelBase::int32_tFromJson(
      val.at(utility::conversions::to_string_t("session_id"))));
}

void UserSessionId::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                                const utility::string_t& prefix) const {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("user_id"), m_User_id));
  multipart->add(ModelBase::toHttpContent(
      namePrefix + utility::conversions::to_string_t("session_id"),
      m_Session_id));
}

void UserSessionId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                                  const utility::string_t& prefix) {
  utility::string_t namePrefix = prefix;
  if (namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) !=
                                   utility::conversions::to_string_t(".")) {
    namePrefix += utility::conversions::to_string_t(".");
  }

  setUserId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("user_id"))));
  setSessionId(ModelBase::int32_tFromHttpContent(
      multipart->getContent(utility::conversions::to_string_t("session_id"))));
}

int32_t UserSessionId::getUserId() const { return m_User_id; }

void UserSessionId::setUserId(int32_t value) { m_User_id = value; }

int32_t UserSessionId::getSessionId() const { return m_Session_id; }

void UserSessionId::setSessionId(int32_t value) { m_Session_id = value; }

}  // namespace model
}  // namespace client
}  // namespace openapitools
}  // namespace org
